# Generated by Django 2.2.11 on 2020-06-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsByAuthor',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_wordpress_api_blogsbyauthor', serialize=False, to='cms.CMSPlugin')),
                ('number_to_display', models.IntegerField(default=4, help_text='The number of blog posts to be displayed')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('featured', 'Featured')], default='grid', max_length=55)),
                ('authors', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BlogsByCategory',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_wordpress_api_blogsbycategory', serialize=False, to='cms.CMSPlugin')),
                ('number_to_display', models.IntegerField(default=4, help_text='The number of blog posts to be displayed')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('featured', 'Featured')], default='grid', max_length=55)),
                ('categories', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BlogsByTag',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_wordpress_api_blogsbytag', serialize=False, to='cms.CMSPlugin')),
                ('number_to_display', models.IntegerField(default=4, help_text='The number of blog posts to be displayed')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('featured', 'Featured')], default='grid', max_length=55)),
                ('tags', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LatestBlogs',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_wordpress_api_latestblogs', serialize=False, to='cms.CMSPlugin')),
                ('number_to_display', models.IntegerField(default=4, help_text='The number of blog posts to be displayed')),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List'), ('featured', 'Featured')], default='grid', max_length=55)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
